# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/guilherme/workspace/balloon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/guilherme/workspace/balloon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilherme/workspace/balloon/CMakeFiles /home/guilherme/workspace/balloon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/guilherme/workspace/balloon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyGame

# Build rule for target.
MyGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyGame
.PHONY : MyGame

# fast build rule for target.
MyGame/fast:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/build
.PHONY : MyGame/fast

#=============================================================================
# Target rules for targets named MyGame_PRE_BUILD

# Build rule for target.
MyGame_PRE_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyGame_PRE_BUILD
.PHONY : MyGame_PRE_BUILD

# fast build rule for target.
MyGame_PRE_BUILD/fast:
	$(MAKE) -f CMakeFiles/MyGame_PRE_BUILD.dir/build.make CMakeFiles/MyGame_PRE_BUILD.dir/build
.PHONY : MyGame_PRE_BUILD/fast

#=============================================================================
# Target rules for targets named MyGame_CORE_PRE_BUILD

# Build rule for target.
MyGame_CORE_PRE_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MyGame_CORE_PRE_BUILD
.PHONY : MyGame_CORE_PRE_BUILD

# fast build rule for target.
MyGame_CORE_PRE_BUILD/fast:
	$(MAKE) -f CMakeFiles/MyGame_CORE_PRE_BUILD.dir/build.make CMakeFiles/MyGame_CORE_PRE_BUILD.dir/build
.PHONY : MyGame_CORE_PRE_BUILD/fast

#=============================================================================
# Target rules for targets named bullet

# Build rule for target.
bullet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bullet
.PHONY : bullet

# fast build rule for target.
bullet/fast:
	$(MAKE) -f cocos2d/external/bullet/CMakeFiles/bullet.dir/build.make cocos2d/external/bullet/CMakeFiles/bullet.dir/build
.PHONY : bullet/fast

#=============================================================================
# Target rules for targets named recast

# Build rule for target.
recast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recast
.PHONY : recast

# fast build rule for target.
recast/fast:
	$(MAKE) -f cocos2d/external/recast/CMakeFiles/recast.dir/build.make cocos2d/external/recast/CMakeFiles/recast.dir/build
.PHONY : recast/fast

#=============================================================================
# Target rules for targets named tinyxml2

# Build rule for target.
tinyxml2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml2
.PHONY : tinyxml2

# fast build rule for target.
tinyxml2/fast:
	$(MAKE) -f cocos2d/external/tinyxml2/CMakeFiles/tinyxml2.dir/build.make cocos2d/external/tinyxml2/CMakeFiles/tinyxml2.dir/build
.PHONY : tinyxml2/fast

#=============================================================================
# Target rules for targets named unzip

# Build rule for target.
unzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unzip
.PHONY : unzip

# fast build rule for target.
unzip/fast:
	$(MAKE) -f cocos2d/external/unzip/CMakeFiles/unzip.dir/build.make cocos2d/external/unzip/CMakeFiles/unzip.dir/build
.PHONY : unzip/fast

#=============================================================================
# Target rules for targets named flatbuffers

# Build rule for target.
flatbuffers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flatbuffers
.PHONY : flatbuffers

# fast build rule for target.
flatbuffers/fast:
	$(MAKE) -f cocos2d/external/flatbuffers/CMakeFiles/flatbuffers.dir/build.make cocos2d/external/flatbuffers/CMakeFiles/flatbuffers.dir/build
.PHONY : flatbuffers/fast

#=============================================================================
# Target rules for targets named xxhash

# Build rule for target.
xxhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xxhash
.PHONY : xxhash

# fast build rule for target.
xxhash/fast:
	$(MAKE) -f cocos2d/external/xxhash/CMakeFiles/xxhash.dir/build.make cocos2d/external/xxhash/CMakeFiles/xxhash.dir/build
.PHONY : xxhash/fast

#=============================================================================
# Target rules for targets named cocos2d

# Build rule for target.
cocos2d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cocos2d
.PHONY : cocos2d

# fast build rule for target.
cocos2d/fast:
	$(MAKE) -f cocos2d/cocos/CMakeFiles/cocos2d.dir/build.make cocos2d/cocos/CMakeFiles/cocos2d.dir/build
.PHONY : cocos2d/fast

#=============================================================================
# Target rules for targets named cocos2dInternal

# Build rule for target.
cocos2dInternal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cocos2dInternal
.PHONY : cocos2dInternal

# fast build rule for target.
cocos2dInternal/fast:
	$(MAKE) -f cocos2d/cocos/CMakeFiles/cocos2dInternal.dir/build.make cocos2d/cocos/CMakeFiles/cocos2dInternal.dir/build
.PHONY : cocos2dInternal/fast

Classes/AppDelegate.o: Classes/AppDelegate.cpp.o

.PHONY : Classes/AppDelegate.o

# target to build an object file
Classes/AppDelegate.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.o
.PHONY : Classes/AppDelegate.cpp.o

Classes/AppDelegate.i: Classes/AppDelegate.cpp.i

.PHONY : Classes/AppDelegate.i

# target to preprocess a source file
Classes/AppDelegate.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.i
.PHONY : Classes/AppDelegate.cpp.i

Classes/AppDelegate.s: Classes/AppDelegate.cpp.s

.PHONY : Classes/AppDelegate.s

# target to generate assembly for a file
Classes/AppDelegate.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AppDelegate.cpp.s
.PHONY : Classes/AppDelegate.cpp.s

Classes/AssetsHelper.o: Classes/AssetsHelper.cpp.o

.PHONY : Classes/AssetsHelper.o

# target to build an object file
Classes/AssetsHelper.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AssetsHelper.cpp.o
.PHONY : Classes/AssetsHelper.cpp.o

Classes/AssetsHelper.i: Classes/AssetsHelper.cpp.i

.PHONY : Classes/AssetsHelper.i

# target to preprocess a source file
Classes/AssetsHelper.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AssetsHelper.cpp.i
.PHONY : Classes/AssetsHelper.cpp.i

Classes/AssetsHelper.s: Classes/AssetsHelper.cpp.s

.PHONY : Classes/AssetsHelper.s

# target to generate assembly for a file
Classes/AssetsHelper.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/AssetsHelper.cpp.s
.PHONY : Classes/AssetsHelper.cpp.s

Classes/Balloon.o: Classes/Balloon.cpp.o

.PHONY : Classes/Balloon.o

# target to build an object file
Classes/Balloon.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Balloon.cpp.o
.PHONY : Classes/Balloon.cpp.o

Classes/Balloon.i: Classes/Balloon.cpp.i

.PHONY : Classes/Balloon.i

# target to preprocess a source file
Classes/Balloon.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Balloon.cpp.i
.PHONY : Classes/Balloon.cpp.i

Classes/Balloon.s: Classes/Balloon.cpp.s

.PHONY : Classes/Balloon.s

# target to generate assembly for a file
Classes/Balloon.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Balloon.cpp.s
.PHONY : Classes/Balloon.cpp.s

Classes/GameScene.o: Classes/GameScene.cpp.o

.PHONY : Classes/GameScene.o

# target to build an object file
Classes/GameScene.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GameScene.cpp.o
.PHONY : Classes/GameScene.cpp.o

Classes/GameScene.i: Classes/GameScene.cpp.i

.PHONY : Classes/GameScene.i

# target to preprocess a source file
Classes/GameScene.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GameScene.cpp.i
.PHONY : Classes/GameScene.cpp.i

Classes/GameScene.s: Classes/GameScene.cpp.s

.PHONY : Classes/GameScene.s

# target to generate assembly for a file
Classes/GameScene.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GameScene.cpp.s
.PHONY : Classes/GameScene.cpp.s

Classes/GeneralHelper.o: Classes/GeneralHelper.cpp.o

.PHONY : Classes/GeneralHelper.o

# target to build an object file
Classes/GeneralHelper.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GeneralHelper.cpp.o
.PHONY : Classes/GeneralHelper.cpp.o

Classes/GeneralHelper.i: Classes/GeneralHelper.cpp.i

.PHONY : Classes/GeneralHelper.i

# target to preprocess a source file
Classes/GeneralHelper.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GeneralHelper.cpp.i
.PHONY : Classes/GeneralHelper.cpp.i

Classes/GeneralHelper.s: Classes/GeneralHelper.cpp.s

.PHONY : Classes/GeneralHelper.s

# target to generate assembly for a file
Classes/GeneralHelper.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/GeneralHelper.cpp.s
.PHONY : Classes/GeneralHelper.cpp.s

Classes/Language.o: Classes/Language.cpp.o

.PHONY : Classes/Language.o

# target to build an object file
Classes/Language.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Language.cpp.o
.PHONY : Classes/Language.cpp.o

Classes/Language.i: Classes/Language.cpp.i

.PHONY : Classes/Language.i

# target to preprocess a source file
Classes/Language.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Language.cpp.i
.PHONY : Classes/Language.cpp.i

Classes/Language.s: Classes/Language.cpp.s

.PHONY : Classes/Language.s

# target to generate assembly for a file
Classes/Language.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/Language.cpp.s
.PHONY : Classes/Language.cpp.s

Classes/LostLayer.o: Classes/LostLayer.cpp.o

.PHONY : Classes/LostLayer.o

# target to build an object file
Classes/LostLayer.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/LostLayer.cpp.o
.PHONY : Classes/LostLayer.cpp.o

Classes/LostLayer.i: Classes/LostLayer.cpp.i

.PHONY : Classes/LostLayer.i

# target to preprocess a source file
Classes/LostLayer.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/LostLayer.cpp.i
.PHONY : Classes/LostLayer.cpp.i

Classes/LostLayer.s: Classes/LostLayer.cpp.s

.PHONY : Classes/LostLayer.s

# target to generate assembly for a file
Classes/LostLayer.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/LostLayer.cpp.s
.PHONY : Classes/LostLayer.cpp.s

Classes/TitleScene.o: Classes/TitleScene.cpp.o

.PHONY : Classes/TitleScene.o

# target to build an object file
Classes/TitleScene.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/TitleScene.cpp.o
.PHONY : Classes/TitleScene.cpp.o

Classes/TitleScene.i: Classes/TitleScene.cpp.i

.PHONY : Classes/TitleScene.i

# target to preprocess a source file
Classes/TitleScene.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/TitleScene.cpp.i
.PHONY : Classes/TitleScene.cpp.i

Classes/TitleScene.s: Classes/TitleScene.cpp.s

.PHONY : Classes/TitleScene.s

# target to generate assembly for a file
Classes/TitleScene.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/Classes/TitleScene.cpp.s
.PHONY : Classes/TitleScene.cpp.s

proj.linux/main.o: proj.linux/main.cpp.o

.PHONY : proj.linux/main.o

# target to build an object file
proj.linux/main.cpp.o:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/proj.linux/main.cpp.o
.PHONY : proj.linux/main.cpp.o

proj.linux/main.i: proj.linux/main.cpp.i

.PHONY : proj.linux/main.i

# target to preprocess a source file
proj.linux/main.cpp.i:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/proj.linux/main.cpp.i
.PHONY : proj.linux/main.cpp.i

proj.linux/main.s: proj.linux/main.cpp.s

.PHONY : proj.linux/main.s

# target to generate assembly for a file
proj.linux/main.cpp.s:
	$(MAKE) -f CMakeFiles/MyGame.dir/build.make CMakeFiles/MyGame.dir/proj.linux/main.cpp.s
.PHONY : proj.linux/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... MyGame"
	@echo "... MyGame_PRE_BUILD"
	@echo "... rebuild_cache"
	@echo "... MyGame_CORE_PRE_BUILD"
	@echo "... bullet"
	@echo "... recast"
	@echo "... tinyxml2"
	@echo "... unzip"
	@echo "... flatbuffers"
	@echo "... xxhash"
	@echo "... cocos2d"
	@echo "... cocos2dInternal"
	@echo "... Classes/AppDelegate.o"
	@echo "... Classes/AppDelegate.i"
	@echo "... Classes/AppDelegate.s"
	@echo "... Classes/AssetsHelper.o"
	@echo "... Classes/AssetsHelper.i"
	@echo "... Classes/AssetsHelper.s"
	@echo "... Classes/Balloon.o"
	@echo "... Classes/Balloon.i"
	@echo "... Classes/Balloon.s"
	@echo "... Classes/GameScene.o"
	@echo "... Classes/GameScene.i"
	@echo "... Classes/GameScene.s"
	@echo "... Classes/GeneralHelper.o"
	@echo "... Classes/GeneralHelper.i"
	@echo "... Classes/GeneralHelper.s"
	@echo "... Classes/Language.o"
	@echo "... Classes/Language.i"
	@echo "... Classes/Language.s"
	@echo "... Classes/LostLayer.o"
	@echo "... Classes/LostLayer.i"
	@echo "... Classes/LostLayer.s"
	@echo "... Classes/TitleScene.o"
	@echo "... Classes/TitleScene.i"
	@echo "... Classes/TitleScene.s"
	@echo "... proj.linux/main.o"
	@echo "... proj.linux/main.i"
	@echo "... proj.linux/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

